### ISSUE TITLE
Bug in the rk: A superuser (root) privileges required for the user kernels location ~/.ipython/kernels

### ISSUE THREAD

**Issue by zonca** [korniichuk/rk#2]
wouldn't it be possible to save kernelspecs in `~/.ipython/kernels`?

**Comment by korniichuk** [comment]
The default kernels location in the rk: `/usr/local/share/jupyter/kernels`.
Change the default kernels location: `$ sudo gedit /usr/local/lib/python2.7/dist-packages/rk/config/rk.ini`.

`rk.ini`:

<pre>
config_argparse_rel_path = "config/argparse.txt"
config_kernels_rel_path = "config/kernels.json"
config_messages_rel_path = "config/messages.txt"
connection_file = "{connection_file}"
display_name = "Template"
img_location = "resources/img"
interpreter = "python"
kernel_name = "template"
<b>kernels_location = "/usr/local/share/jupyter/kernels"</b>
language = "python"
logo_name_srt = "logo-{0}x{0}.png"
remote_host = "remote_username@remote_host"
rk_log_location = "/tmp/rk/log"
script = "rkscript"
</pre>

And thanks, we must change code, because superuser (root) privileges also required for `~/.ipython/kernels` dir o.O.

**Comment by korniichuk** [comment]
Fixed bug in the rk: a superuser (root) privileges required for the user kernels location `~/.ipython/kernels`.
Added new section **Kernels location** to README: https://github.com/korniichuk/rk#kernels-location

**Comment by dereneaton** [comment]
Might be worth mentioning in the docs that the `rk.ini` file can end up here: `anaconda/lib/python2.7/site-packages/rk/config/rk.ini` if using a conda-installed pip, and it doesn't require superuser privileges to change. For me `kernel.json` ended up here: `.ipython/kernels/template/kernel.json`. 

Once I figured that out everything went smoothly!

**Comment by Phyks** [comment]
Would not it be worth it setting kernels in local folder if root access is not provided? Sounds like a better default config to me.
